name: Rust CI Test

on:
  push:
    branches: [ master ]
    paths:
      - '**.rs'
  pull_request:
    branches: [ master ]
    paths:
      - '**.rs'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
#     - name: Tests
#       run: cargo test --release